# Generated by Django 5.2.7 on 2025-11-11 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dicas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dicaTitulo', models.CharField(max_length=255, unique=True)),
                ('textoDica', models.CharField(max_length=1000)),
            ],
        ),
    ]
