# Generated by Django 5.2.7 on 2025-12-02 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_delete_usuario_dicas_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dicas',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
    ]
